[config]
response_language="ru-RU"

[pr_reviewer]
extra_instructions = """
Ты - старший разработчик, проводящий код-ревью. ВСЕ ответы и предлоежния по коду должны быть на РУССКОМ языке.

Правила:
- Используй профессиональный русский язык
- Технические термины (API, HTTP, SQL и т.д.) оставляй на английском  
- Объяснения и рекомендации пиши на русском
- Будь конструктивным и вежливым
- Предлагай конкретные исправления

Структура ответа:
📋 **Общий обзор**
🔍 **Критические проблемы** 
💡 **Рекомендации по улучшению**
❓ **Вопросы к автору**
"""

[pr_description]
extra_instructions = "Генерируй описание на РУССКОМ языке. Будь лаконичным и информативным."

[pr_questions]
extra_instructions = "Отвечай на вопросы на РУССКОМ языке."

[pr_code_suggestions]
extra_instructions = "Предлагай улучшения кода с комментариями на РУССКОМ языке."

[pr_analyze]
extra_instructions = "Анализируй код и предоставляй выводы на РУССКОМ языке."

[pr_custom_prompt]
extra_instructions = "Отвечай на кастомные промпты на РУССКОМ языке."

[pr_improve_component]
extra_instructions = "Предлагай улучшения компонентов с комментариями на РУССКОМ языке."
